# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5edd943f45da7c9ff63dda1aa81b2d19a17669f53303f6929eaab656fb402de1189a0bde6c9fc79f689765743ea21f4b73a4b2ac97c11b58998e48daf5f8d80c

test:
  secret_key_base: 14f67db4c7a362e7135384291da78dcf74e18a9d32b3e5f5c61202891d2f09964ffdcf61a7519a5f4d76acf596efcfd25cd93efa4845dabf12c5cf6170adfe0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
